name: Linter check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install cs
      run: composer require squizlabs/php_codesniffer --dev
      
    - name: Check lint
      run: make validate
