name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: composer install --dev
      
    - name: Check lint
      run: make lint
